import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./utils/theme-provider";
import { CursorLight } from "./utils/CursorLight";
import BackToTopButton from "../components/ui/BackToTopButton";
// import Footer from "./components/ui/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <title>Portfolio</title>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CursorLight />
        <ThemeProvider 
          attribute="class"
          defaultTheme="system"
          enableSystem>
          {children}
          {/* <Footer /> */}
          <BackToTopButton />
        </ThemeProvider>
      </body>
    </html>
  );
}
